version: '3'

services:
  web:
    build: .
    env_file: ./.env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 arpansahu_dot_me.wsgi"
    image: arpansahu_dot_me
    container_name: arpansahu_dot_me
    volumes:
      - .:/arpansahu_dot_me
    ports:
      - "8000:8000"
    restart: unless-stopped