apiVersion: v1
kind: Service
metadata:
  name: arpansahu-dot-me-service
spec:
  selector:
    app: arpansahu-dot-me
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000
  type: NodePort